"""
This type stub file was generated by pyright.
"""

from langchain.schema import SystemMessage
from langchain_core.tools import BaseTool

def generate_tool_descriptions(tools: list[BaseTool], disallowed_tools: list[str] | None = ...) -> list[str]:
    """
    Generates a list of formatted tool descriptions, excluding disallowed tools.

    Args:
        tools: The list of available BaseTool objects.
        disallowed_tools: A list of tool names to exclude.

    Returns:
        A list of strings, each describing a tool in the format "- tool_name: description".
    """
    ...

def build_system_prompt_content(template: str, tool_description_lines: list[str], additional_instructions: str | None = ...) -> str:
    """
    Builds the final system prompt string using a template, tool descriptions,
    and optional additional instructions.

    Args:
        template: The system prompt template string (must contain '{tool_descriptions}').
        tool_description_lines: A list of formatted tool description strings.
        additional_instructions: Optional extra instructions to append.

    Returns:
        The fully formatted system prompt content string.
    """
    ...

def create_system_message(tools: list[BaseTool], system_prompt_template: str, server_manager_template: str, use_server_manager: bool, disallowed_tools: list[str] | None = ..., user_provided_prompt: str | None = ..., additional_instructions: str | None = ...) -> SystemMessage:
    """
    Creates the final SystemMessage object for the agent.

    Handles selecting the correct template, generating tool descriptions,
    and incorporating user overrides and additional instructions.

    Args:
        tools: List of available tools.
        system_prompt_template: The default system prompt template.
        server_manager_template: The template to use when server manager is active.
        use_server_manager: Flag indicating if server manager mode is enabled.
        disallowed_tools: List of tool names to exclude.
        user_provided_prompt: A complete system prompt provided by the user, overriding templates.
        additional_instructions: Extra instructions to append to the template-based prompt.

    Returns:
        A SystemMessage object containing the final prompt content.
    """
    ...

