"""
This type stub file was generated by pyright.
"""

from typing import Any, TextIO
from mcp import StdioServerParameters
from .base import ConnectionManager

"""
StdIO connection management for MCP implementations.

This module provides a connection manager for stdio-based MCP connections
that ensures proper task isolation and resource cleanup.
"""
class StdioConnectionManager(ConnectionManager[tuple[Any, Any]]):
    """Connection manager for stdio-based MCP connections.

    This class handles the proper task isolation for stdio_client context managers
    to prevent the "cancel scope in different task" error. It runs the stdio_client
    in a dedicated task and manages its lifecycle.
    """
    def __init__(self, server_params: StdioServerParameters, errlog: TextIO = ...) -> None:
        """Initialize a new stdio connection manager.

        Args:
            server_params: The parameters for the stdio server
            errlog: The error log stream
        """
        ...
    


