"""
This type stub file was generated by pyright.
"""

from importlib.metadata import version
from .logging import Logger, MCP_USE_DEBUG, logger
from . import observability
from .agents.mcpagent import MCPAgent
from .client import MCPClient
from .config import load_config_file
from .connectors import BaseConnector, HttpConnector, StdioConnector, WebSocketConnector
from .session import MCPSession

"""
mcp_use - An MCP library for LLMs.

This library provides a unified interface for connecting different LLMs
to MCP tools through existing LangChain adapters.
"""
__version__ = ...
__all__ = ["MCPAgent", "MCPClient", "MCPSession", "BaseConnector", "StdioConnector", "WebSocketConnector", "HttpConnector", "load_config_file", "logger", "MCP_USE_DEBUG", "Logger", "set_debug", "observability"]
def set_debug(debug=...): # -> None:
    """Set the debug mode for mcp_use.

    Args:
        debug: Whether to enable debug mode (default: True)
    """
    ...

