"""
This type stub file was generated by pyright.
"""

from typing import ClassVar
from langchain_core.tools import BaseTool

class MCPServerTool(BaseTool):
    """Base tool for MCP server operations."""
    name: ClassVar[str] = ...
    description: ClassVar[str] = ...
    def __init__(self, server_manager) -> None:
        """Initialize with server manager."""
        ...
    
    @property
    def server_manager(self): # -> Any:
        ...
    


