"""
This type stub file was generated by pyright.
"""

from typing import ClassVar
from pydantic import BaseModel
from .base_tool import MCPServerTool

class ServerActionInput(BaseModel):
    """Base input for server-related actions"""
    server_name: str = ...


class ConnectServerTool(MCPServerTool):
    """Tool for connecting to a specific MCP server."""
    name: ClassVar[str] = ...
    description: ClassVar[str] = ...
    args_schema: ClassVar[type[BaseModel]] = ...


