"""
This type stub file was generated by pyright.
"""

from typing import ClassVar
from pydantic import BaseModel
from .base_tool import MCPServerTool

class DisconnectServerInput(BaseModel):
    """Empty input for disconnecting from the current server"""
    ...


class DisconnectServerTool(MCPServerTool):
    """Tool for disconnecting from the currently active MCP server."""
    name: ClassVar[str] = ...
    description: ClassVar[str] = ...
    args_schema: ClassVar[type[BaseModel]] = ...


