"""
This type stub file was generated by pyright.
"""

from typing import ClassVar
from pydantic import BaseModel
from .base_tool import MCPServerTool

class CurrentServerInput(BaseModel):
    """Empty input for checking current server"""
    ...


class GetActiveServerTool(MCPServerTool):
    """Tool for getting the currently active MCP server."""
    name: ClassVar[str] = ...
    description: ClassVar[str] = ...
    args_schema: ClassVar[type[BaseModel]] = ...


