"""
This type stub file was generated by pyright.
"""

from typing import ClassVar
from pydantic import BaseModel
from .base_tool import MCPServerTool

class listServersInput(BaseModel):
    """Empty input for listing available servers"""
    ...


class ListServersTool(MCPServerTool):
    """Tool for listing available MCP servers."""
    name: ClassVar[str] = ...
    description: ClassVar[str] = ...
    args_schema: ClassVar[type[BaseModel]] = ...


