"""
This type stub file was generated by pyright.
"""

from typing import NotRequired, TypedDict

"""Type definitions for sandbox-related configurations."""
class SandboxOptions(TypedDict):
    """Configuration options for sandbox execution.

    This type defines the configuration options available when running
    MCP servers in a sandboxed environment (e.g., using E2B).
    """
    api_key: str
    sandbox_template_id: NotRequired[str]
    supergateway_command: NotRequired[str]
    ...


