"""
This type stub file was generated by pyright.
"""

from .base import BaseAdapter

"""
LangChain adapter for MCP tools.

This module provides utilities to convert MCP tools to LangChain tools.
"""
class LangChainAdapter(BaseAdapter):
    """Adapter for converting MCP tools to LangChain tools."""
    def __init__(self, disallowed_tools: list[str] | None = ...) -> None:
        """Initialize a new LangChain adapter.

        Args:
            disallowed_tools: list of tool names that should not be available.
        """
        ...
    
    def fix_schema(self, schema: dict) -> dict:
        """Convert JSON Schema 'type': ['string', 'null'] to 'anyOf' format.

        Args:
            schema: The JSON schema to fix.

        Returns:
            The fixed JSON schema.
        """
        ...
    


